### ISSUE TITLE
Should `path` be included?

### ISSUE THREAD

**Issue by canadaduane** [nphollon/typed-svg#1]
So there's a separate library that folkertdev is making that makes a DSL for paths: http://package.elm-lang.org/packages/folkertdev/svg-path-dsl/latest

It seems like this would be nice to have in one library. Or perhaps intimately linked so they work nicely together. Is this something you have thought about? I'm considering working on this problem (joining the libraries together), but I'd rather not be a 3rd wheel here :)

**Comment by nphollon** [comment]
You should absolutely go for it! I only spent a couple days on this project (didn't even get as far as publishing it to elm-package), and I doubt I am going to come back to it. So you are welcome to fork the code or scavenge any pieces that seem like good ideas :-)
